# If you come from bash you might have to change your $PATH.
# export PATH=$HOME/bin:/usr/local/bin:$PATH

# Path to your oh-my-zsh installation.
export ZSH="$HOME/.oh-my-zsh"

# Set name of the theme to load --- if set to "random", it will
# load a random theme each time oh-my-zsh is loaded, in which case,
# to know which specific one was loaded, run: echo $RANDOM_THEME
# See https://github.com/ohmyzsh/ohmyzsh/wiki/Themes
ZSH_THEME="mortalscumbag"

# Set list of themes to pick from when loading at random
# Setting this variable when ZSH_THEME=random will cause zsh to load
# a theme from this variable instead of looking in $ZSH/themes/
# If set to an empty array, this variable will have no effect.
# ZSH_THEME_RANDOM_CANDIDATES=( "robbyrussell" "agnoster" )

# Uncomment the following line to use case-sensitive completion.
# CASE_SENSITIVE="true"

# Uncomment the following line to use hyphen-insensitive completion.
# Case-sensitive completion must be off. _ and - will be interchangeable.
# HYPHEN_INSENSITIVE="true"

# Uncomment one of the following lines to change the auto-update behavior
# zstyle ':omz:update' mode disabled  # disable automatic updates
# zstyle ':omz:update' mode auto      # update automatically without asking
# zstyle ':omz:update' mode reminder  # just remind me to update when it's time

# Uncomment the following line to change how often to auto-update (in days).
# zstyle ':omz:update' frequency 13

# Uncomment the following line if pasting URLs and other text is messed up.
# DISABLE_MAGIC_FUNCTIONS="true"

# Uncomment the following line to disable colors in ls.
# DISABLE_LS_COLORS="true"

# Uncomment the following line to disable auto-setting terminal title.
# DISABLE_AUTO_TITLE="true"

# Uncomment the following line to enable command auto-correction.
# ENABLE_CORRECTION="true"

# Uncomment the following line to display red dots whilst waiting for completion.
# You can also set it to another string to have that shown instead of the default red dots.
# e.g. COMPLETION_WAITING_DOTS="%F{yellow}waiting...%f"
# Caution: this setting can cause issues with multiline prompts in zsh < 5.7.1 (see #5765)
# COMPLETION_WAITING_DOTS="true"

# Uncomment the following line if you want to disable marking untracked files
# under VCS as dirty. This makes repository status check for large repositories
# much, much faster.
# DISABLE_UNTRACKED_FILES_DIRTY="true"

# Uncomment the following line if you want to change the command execution time
# stamp shown in the history command output.
# You can set one of the optional three formats:
# "mm/dd/yyyy"|"dd.mm.yyyy"|"yyyy-mm-dd"
# or set a custom format using the strftime function format specifications,
# see 'man strftime' for details.
# HIST_STAMPS="mm/dd/yyyy"

# Would you like to use another custom folder than $ZSH/custom?
# ZSH_CUSTOM=/path/to/new-custom-folder

# Which plugins would you like to load?
# Standard plugins can be found in $ZSH/plugins/
# Custom plugins may be added to $ZSH_CUSTOM/plugins/
# Example format: plugins=(rails git textmate ruby lighthouse)
# Add wisely, as too many plugins slow down shell startup.
plugins=(
    aliases
    colored-man-pages
    emoji
    copyfile
    copypath
    encode64
    fzf
    genpass
    qrcode
    copybuffer
    fancy-ctrl-z
    sudo
    git
    git-lfs
    isodate
    npm
    ripgrep
    rust
    nvm
    zig-shell-completions
    zoxide
)
zstyle ':omz:plugins:nvm' lazy yes
ZOXIDE_CMD_OVERRIDE="z"

## Interesting plugins

### ZSH Extensions
# - aliases: `als` to show active aliases, `als --group` to show alias groups.
#       Python script. May be slow.
# - colored-man-pages: Adds the `colored` command to color output.
#       Shadows `man` w/ `colored man`.
# - emoji: Unicode emoji in the terminal.
# - per-directory-history: Like it says on the tin. Toggleable between dir and global with `Ctrl+G`.

### ZSH Prompt modifiers
# - git-prompt: Verbose terminal prompt for Git repository status.
#       Looks heavy-weight. Probably slow?
# - nodeenv: Add Node version information to the terminal prompt.

### Helper functions
# - copyfile: Adds `copyfile <file>` to copy the contents of a file to the system clipboard.
# - copypath: Adds `copypath [path]` to copy the given directory to the system clipboard.
# - encode64: Adds `e64`, `d64`, etc. to encode to or decode from base64.
# - genpass: Adds `genpass-*` to generate random passwords/passphrases.
# - qrcode: Adds `qrcode`, `qrsvg`; generate QR codes in a terminal.
#       Uses `curl https://qrcode.show/`.

### Keybindings
# - copybuffer: `Ctrl+O` to copy the current command buffer to the system clipboard.
# - fancy-ctrl-z: `Ctrl+Z` to background a process and `Ctrl+Z` to foreground it.
# - tehfuck: `Esc+Esc` to run `fuck`.
# - sudo: `Esc+Esc` to prepend `sudo` to the last run command.
# - man: `Esc + man` to prepend `man` before the last run command.

### Aliases and Completions
# - git: Aliases for Git.
# - git-lfs: Aliases for the Git Large File Storage extension.
# - isodate: Aliases for printing ISO 8601 formatted dates.
# - npm: Aliases and completions for `npm`.
# - tig: Aliases for tig.
# - dnote: Completions for `dnote`; terminal-based note taker.
# - gh: Completions for the GitHub CLI.
# - httpie: Completions for `http`; a modern terminal-based HTTP client.
# - ripgrep: Completions for ripgrep.
# - rust: Completions for `rustc`, `rustup`, and `cargo` .
# - taskwarrior: Completions for TaskWarrior's `task`; terminal-based TODO list.
# - watson: Completions for `watson`; terminal-based time-tracking.

### Sourcing/Init'ing + Completions and Aliases
# - nvm: Sources `nvm` and adds completions.
#       Run with `zstyle ':omz:plugins:nvm' lazy yes` to speed up zsh startup.
#       Don't source "$NVM_DIR/nvm.sh" or "$NVM_DIR/bash_completion" when running.
# - zoxide: Initializes zoxide; the most recent autojump/z/v/fasd tool. (`z` but in Rust.)
#   - fzf: Completions and keybindings for `fzf`; fuzzy finder for the terminal.
#   - zsh-interactive-cd: `fzf` applied to `cd` tab completion.

### Custom plugins
# - zig-shell-completions: Completions for the `zig` CLI
#       https://github.com/ziglang/shell-completions
#       git clone https://github.com/ziglang/shell-completions $ZSH/custom/plugins/zig-shell-completions

source $ZSH/oh-my-zsh.sh

# User configuration

# export MANPATH="/usr/local/man:$MANPATH"

# You may need to manually set your language environment
# export LANG=en_US.UTF-8

# Preferred editor for local and remote sessions
# if [[ -n $SSH_CONNECTION ]]; then
#   export EDITOR='vim'
# else
#   export EDITOR='mvim'
# fi

# Compilation flags
# export ARCHFLAGS="-arch x86_64"

# Set personal aliases, overriding those provided by oh-my-zsh libs,
# plugins, and themes. Aliases can be placed here, though oh-my-zsh
# users are encouraged to define aliases within the ZSH_CUSTOM folder.
# For a full list of active aliases, run `alias`.
#
# Example aliases
# alias zshconfig="mate ~/.zshrc"
# alias ohmyzsh="mate ~/.oh-my-zsh"


# # Add the dotnet-install.sh'd sdks to the PATH ...
# export PATH="$HOME/.dotnet:$HOME/.dotnet/tools:$PATH"
# # ... and define the DOTNET_ROOT path based on that binary.
# export DOTNET_ROOT=$(dirname $(which dotnet))

# # Set up pyenv
# export PYENV_ROOT="$HOME/.pyenv"
# export PATH="$PYENV_ROOT/bin:$PATH"
# eval "$(pyenv init --path)"

# # Set up NVM
# # But actually don't. Let the `nvm` plugin handle it.
# export NVM_DIR="$HOME/.nvm"
# [ -s "$NVM_DIR/nvm.sh" ] && . "$NVM_DIR/nvm.sh"  # This loads nvm
# [ -s "$NVM_DIR/bash_completion" ] && . "$NVM_DIR/bash_completion"  # This loads nvm bash_completion

# Set up rust
if [ -d "$HOME/.cargo/bin" ] ; then
    export PATH="$PATH:$HOME/.cargo/bin"


    # Rustc and Cargo use this environment variable to enable "nightly-like"
    # behavior on stable/beta compilers. Some people in the rust-lang project
    # get very grumpy if you use this escape hatch and pitch all kinds of ways
    # to make life harder for you.
    # See https://github.com/rust-lang/cargo/issues/7088 and linked issues.
    export RUSTC_BOOTSTRAP="1"
    
    # This lets you instruct cargo that it's running from a local compile, actually.
    # Same story as above, except for Cargo it's so it can force the channel in its
    # unit tests to confirm the "rules for thee but not for me" features work as
    # intended, blocking you from enabling unstable features which are nevertheless
    # shipped in the binaries you're running.
    export __CARGO_TEST_CHANNEL_OVERRIDE_DO_NOT_USE_THIS="dev"
fi

# Set up Golang
if [ -d "/usr/local/go" ]; then
    export PATH="$PATH:/usr/local/go/bin"
fi

# Set up Zig
if [ -d "$HOME/.zig" ]; then
    export PATH="$PATH:$HOME/.zig"
fi
if [ -d "${HOME}/Library/Application Support/Code/User/globalStorage/ziglang.vscode-zig/zig_install" ]; then
    export PATH="${PATH}:${HOME}/Library/Application Support/Code/User/globalStorage/ziglang.vscode-zig/zig_install"
fi

# Help Bevy and lldb play nice in VSCode.
# Without this explicit LD_LIBRARY_PATH, attempting to launch a sufficently
# complex Bevy application into an interactive debug session in VSCode results
# in lldb not being able to find Bevy's dynamic .so or even the Rust stdlib.
# It's TBD 1. why this is the case, and 2. what a "sufficiently complex" Bevy
# application is.
if command -v rustup >> /dev/null; then
    export LD_LIBRARY_PATH="$(rustup show home)/toolchains/$(rustup show active-toolchain | cut -d " " -f 1)/lib/"
fi

# Source my chirps and squawks
source ${HOME}/repos/dotfiles/common/chirp/source.sh

alias rf="rm -rf"
alias ll="ls -lAh"
alias la="ls -lah"
alias l1="ls -1"

alias xcc="xclip -r -selection clipboard"

function prg {
    ps aux | rg $@ | less -F -X
}

function hrg {
    history | rg $@ | less -F -X
}

function diffly {
    /usr/bin/diff -w -y $@ -W $(( $(tput cols) - 9 )) --color | colordiff | less -r -N --use-color
}

function unquote {
    sed "s/^\([\"']\)\(.*\)\1\$/\2/g"
}

alias py="python"
alias py2="python2"
alias py3="python3"
alias pypip="python -m pip"
alias py2pip="python2 -m pip"
alias py3pip="python3 -m pip"

alias pye="pyenv"

alias c="pyc"
function pyc {
    python3 -c "from math import *; print($*)"
}

function pp_epoch {
    python3 <<EOF
import time;
if len("$1") == 13:
    print(time.strftime("%Y/%m/%d %H:%M:%S.{} %Z".format($1%1000), time.gmtime($1/1000)))
else:
    print(time.strftime("%Y/%m/%d %H:%M:%S %Z", time.gmtime($1)))
EOF
}
function pp_local_epoch {
    python3 <<EOF
import time;
if len("$1") == 13:
    print(time.strftime("%Y/%m/%d %H:%M:%S.{} %Z".format($1%1000), time.localtime($1/1000)))
else:
    print(time.strftime("%Y/%m/%d %H:%M:%S %Z", time.localtime($1)))
EOF
}
